//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.13 at 11:09:11 PM MSK 
//


package com.soa.navigatorspring.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idFrom" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="idTo" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idFrom",
    "idTo",
    "distance"
})
@XmlRootElement(name = "addRouteBetweenLocationsRequest")
public class AddRouteBetweenLocationsRequest {

    protected long idFrom;
    protected long idTo;
    protected int distance;

    /**
     * Gets the value of the idFrom property.
     * 
     */
    public long getIdFrom() {
        return idFrom;
    }

    /**
     * Sets the value of the idFrom property.
     * 
     */
    public void setIdFrom(long value) {
        this.idFrom = value;
    }

    /**
     * Gets the value of the idTo property.
     * 
     */
    public long getIdTo() {
        return idTo;
    }

    /**
     * Sets the value of the idTo property.
     * 
     */
    public void setIdTo(long value) {
        this.idTo = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     */
    public int getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(int value) {
        this.distance = value;
    }

}
