//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.13 at 11:09:11 PM MSK 
//


package com.soa.navigatorspring.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.service.navigator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.service.navigator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllRoutesRequest }
     * 
     */
    public GetAllRoutesRequest createGetAllRoutesRequest() {
        return new GetAllRoutesRequest();
    }

    /**
     * Create an instance of {@link GetAllRoutesResponse }
     * 
     */
    public GetAllRoutesResponse createGetAllRoutesResponse() {
        return new GetAllRoutesResponse();
    }

    /**
     * Create an instance of {@link GetStat }
     * 
     */
    public GetStat createGetStat() {
        return new GetStat();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link GetAllRoutesBetweenLocationsRequest }
     * 
     */
    public GetAllRoutesBetweenLocationsRequest createGetAllRoutesBetweenLocationsRequest() {
        return new GetAllRoutesBetweenLocationsRequest();
    }

    /**
     * Create an instance of {@link GetAllRoutesBetweenLocationsResponse }
     * 
     */
    public GetAllRoutesBetweenLocationsResponse createGetAllRoutesBetweenLocationsResponse() {
        return new GetAllRoutesBetweenLocationsResponse();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link AddRouteBetweenLocationsRequest }
     * 
     */
    public AddRouteBetweenLocationsRequest createAddRouteBetweenLocationsRequest() {
        return new AddRouteBetweenLocationsRequest();
    }

    /**
     * Create an instance of {@link AddRouteBetweenLocationsResponse }
     * 
     */
    public AddRouteBetweenLocationsResponse createAddRouteBetweenLocationsResponse() {
        return new AddRouteBetweenLocationsResponse();
    }

    /**
     * Create an instance of {@link HelloRequest }
     * 
     */
    public HelloRequest createHelloRequest() {
        return new HelloRequest();
    }

    /**
     * Create an instance of {@link HelloResponse }
     * 
     */
    public HelloResponse createHelloResponse() {
        return new HelloResponse();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link Routes }
     * 
     */
    public Routes createRoutes() {
        return new Routes();
    }

}
