/*
 * This source file was generated by the Gradle 'init' task
 */
package core.rest;

import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.validation.Valid;

import core.model.*;
import core.routes.RoutesManager;
import lombok.extern.slf4j.Slf4j;

import java.util.List;
import java.util.Optional;
import javax.inject.Inject;

@ApplicationPath("/routes")
@Slf4j
public class RestAPI extends Application {

    @Inject
    private RoutesManager rm;

    private final String justOk = "Ok";

    // All Exceptions will be intercepted via ExceptionToStatus class
    private Response okWith(Object entity) {
        return Response.ok(entity).build();
    }

    @GET
    public Response getAllRoutes(
            @QueryParam("page") @DefaultValue("0") int page,
            @QueryParam("size") @DefaultValue("10") int size,
            @QueryParam("sort") List<String> sort,
            @QueryParam("filter") List<String> filters) {

        log.info("Got params:\npage:{}\nsize:{}\nsort:{}\nfilters:{}", page, size, sort, filters);
        return okWith(rm.getRoutes(Optional.of(filters))); // Need apply pages
    }

    @GET
    @Path("/{id}")
    public Response getRoute(@PathParam("page") long id) {
        log.info("Get route by id:{}", id);
        return okWith(rm.getRoute(id));
    }

    @GET
    @Path("/min-id")
    public Response getMinRoute() {
        return okWith(rm.minRoute());
    }

    @GET
    @Path("/distance/count/{value}")
    public Response getRouteCount(@PathParam("value") int value) {
        log.info("Get route with distance value:{}", value);
        return okWith(rm.distanceEqual(value));
    }

    @GET
    @Path("/distance/grater/{value}")
    public Response getRouteAbove(@PathParam("value") int value) {
        log.info("Get route with distance value grater than:{}", value);
        return okWith(rm.distanceGreater(value));
    }

    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    public Response addNewRoute(@Valid Route route) {
        rm.addRoute(route);
        return okWith(justOk);
    }

    @PATCH
    @Consumes(MediaType.APPLICATION_JSON)
    public Response updateRoute(@Valid Route route) {
        log.info("Update route, new route:{}", route);
        rm.updateRoute(route);
        return okWith(justOk);
    }

    @DELETE
    public Response deleteRoute(@PathParam("id") long id) {
        log.info("Delete route with id:{}", id);
        rm.deleteRoute(id);
        return okWith(justOk);
    }
}
