/*
 * This source file was generated by the Gradle 'init' task
 */
package core;

import javax.ws.rs.*;
import javax.ws.rs.core.*;
import javax.ws.rs.core.Response.Status;
import javax.validation.Valid;

import core.helpers.PATCH;
import core.model.*;

import java.util.List;

@ApplicationPath("/routes")
public class RestAPI extends Application {

    @GET
    public Response getAllRoutes(
            @QueryParam("page") @DefaultValue("0") int page,
            @QueryParam("size") @DefaultValue("10") int size,
            @QueryParam("sort") List<String> sort,
            @QueryParam("filter") List<String> filter) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @GET
    @Path("/{id}")
    public Response getRoute(@PathParam("page") int page) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @GET
    @Path("/min-id")
    public Response getMinRoute() {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @GET
    @Path("/distance/count/{value}")
    public Response getRouteCount(@PathParam("value") int value) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @GET
    @Path("/distance/grater/{value}")
    public Response getRouteAbove(@PathParam("value") int value) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    public Response addNewRoute(@Valid Route route) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @PATCH
    @Consumes(MediaType.APPLICATION_JSON)
    public Response updateRoute(@Valid Route route) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

    @DELETE
    public Response deleteRoute(@PathParam("id") int id) {
        return Response.status(Status.INTERNAL_SERVER_ERROR).entity("Not implemented").build();
    }

}
