spring:
  application:
    name: navigator
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false # Don't register with Consul

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    preferIpAddress: true
